# Generated by Django 2.2.1 on 2019-05-23 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=50)),
                ('titulo', models.CharField(max_length=50)),
                ('imagen', models.ImageField(upload_to='proyectos')),
                ('contenido', models.TextField()),
                ('create', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update', models.DateTimeField(auto_now_add=True, verbose_name='Ultima actualización')),
            ],
        ),
    ]
